# Generated by Django 4.0.1 on 2022-02-14 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_post',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
